AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template to create OCP 4 worker nodes with user-data.

Parameters:

  ResourcePrefix:
    Description: Prefix to be added to the starting of each resource name
    Type: String
    ConstraintDescription: Must be a valid prefix for resource names.

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: m4.2xlarge
    AllowedValues:
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5a.2xlarge
      - m4.xlarge
      - m4.2xlarge
      - m5.xlarge
    ConstraintDescription: Must be a valid EC2 instance type.

  AMIId:
    Description: AMI ID for the RHCOS instances
    Type: String
    ConstraintDescription: Must be a valid AMI ID.

  PrivateSubnet1Id:
    Type: String
    Description: Public Subnet ID where the instance will be launched.

  PrivateSubnet2Id:
    Type: String
    Description: Public Subnet ID where the instance will be launched.

  InstanceSecurityGroup:
    Type: String
    Description: Existing EC2 security group.

  UserData:
    Description: Bootstrap merge ignition data
    Type: String
    Default: ""


Resources:

  Worker1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      SubnetId: !Ref PrivateSubnet1Id
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData: !Ref UserData
      Tags:
        - Key: Name
          Value: !Sub "${ResourcePrefix}-worker-1"


  Worker2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMIId
      SubnetId: !Ref PrivateSubnet2Id
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData: !Ref UserData
      Tags:
        - Key: Name
          Value: !Sub "${ResourcePrefix}-worker-2"


Outputs:

  Worker1PrivateIP:
    Description: The public IP address of the Worker1 instance.
    Value: !GetAtt Worker1.PrivateIp

  Worker2PrivateIP:
    Description: The public IP address of the Worker2 instance.
    Value: !GetAtt Worker2.PrivateIp